-- =============================================================================
-- DatabaseBackup_ProjectDevHub.sql
-- Full schema + master/lookup seed data export of the ProjectDevHub SQL Server
-- database, generated by querying sys.tables/sys.columns/sys.foreign_keys/
-- sys.indexes/sys.check_constraints/sys.identity_columns/sys.default_constraints
-- directly against the live database (server DESKTOP-TJ7525D\SQLEXPRESS,
-- database ProjectDevHub) — not derived/guessed from the C# model code.
--
-- Table order below follows FK dependency (parent tables before child tables),
-- verified against the real sys.foreign_keys graph.
--
-- Note: while extracting this backup, three master/lookup tables were found to
-- have mojibake-corrupted Thai text (Core.SystemList rows SOLO/TEAM/FLOW,
-- Project.Departments all 4 rows, Project.TechStackCatalog CatalogId=1) caused
-- by an earlier session running an UPDATE/INSERT script through sqlcmd without
-- specifying a UTF-8 codepage. Those values were corrected in the live database
-- (via a parameterized ADO.NET UPDATE, bypassing console codepage entirely)
-- before this export was taken, so the seed data below reflects the corrected,
-- intended text. A full sweep of every nvarchar/nchar column in every table
-- confirmed no other rows were affected.
--
-- Restore into an empty database with:
--   sqlcmd -S "DESKTOP-TJ7525D\SQLEXPRESS" -U sa -P 1234 -C -d ProjectDevHub -i DatabaseBackup_ProjectDevHub.sql
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Core')     EXEC('CREATE SCHEMA Core');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Project')  EXEC('CREATE SCHEMA Project');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Planning') EXEC('CREATE SCHEMA Planning');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Flow')     EXEC('CREATE SCHEMA Flow');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Testing')  EXEC('CREATE SCHEMA Testing');
GO

-- =============================================================================
-- SECTION 1 — CREATE TABLE (ordered so every FK's parent table already exists)
-- =============================================================================

-- ---------- Core.Users ----------
CREATE TABLE Core.Users (
    UserId              INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    EmpId               VARCHAR(20)  NOT NULL,
    PasswordHash        VARCHAR(255) NOT NULL,
    FullName            NVARCHAR(100) NOT NULL,
    DivisionName        NVARCHAR(100) NULL,
    DepartmentName      NVARCHAR(100) NULL,
    SectionName         NVARCHAR(100) NULL,
    UserLevel           INT NOT NULL DEFAULT ((1)),
    IsSuperAdmin        BIT NOT NULL DEFAULT ((0)),
    IsSuspended         BIT NOT NULL DEFAULT ((0)),
    IsOnline            BIT NOT NULL DEFAULT ((0)),
    CurrentSessionId    VARCHAR(100) NULL,
    ComputerName        VARCHAR(255) NULL,
    IpAddress           VARCHAR(45)  NULL,
    LastLoginDate       DATETIMEOFFSET(7) NULL,
    IsActive            BIT NOT NULL DEFAULT ((1)),
    CreatedDate         DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate         DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Core.SystemList ----------
CREATE TABLE Core.SystemList (
    SystemId     VARCHAR(50) NOT NULL PRIMARY KEY,
    SystemName   NVARCHAR(100) NOT NULL,
    Description  NVARCHAR(255) NULL,
    IsActive     BIT NOT NULL DEFAULT ((1)),
    CreatedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Core.Permissions ----------
CREATE TABLE Core.Permissions (
    PermissionId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId        INT NOT NULL,
    SystemId      VARCHAR(50) NOT NULL,
    CanView       BIT NOT NULL DEFAULT ((0)),
    CanAdd        BIT NOT NULL DEFAULT ((0)),
    CanEdit       BIT NOT NULL DEFAULT ((0)),
    CanDelete     BIT NOT NULL DEFAULT ((0)),
    CanApprove    BIT NOT NULL DEFAULT ((0)),
    CanReject     BIT NOT NULL DEFAULT ((0)),
    CreatedDate   DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate   DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Core.AuditLogs ----------
CREATE TABLE Core.AuditLogs (
    LogId            BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId           INT NULL,
    SystemId         VARCHAR(50) NOT NULL,
    ActionType       VARCHAR(50) NOT NULL,
    LogDescription   NVARCHAR(MAX) NULL,
    LogRef           NVARCHAR(100) NULL,
    IpAddress        VARCHAR(45) NULL,
    ComputerName     VARCHAR(255) NULL,
    LogDate          DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.ProjectTypes ----------
CREATE TABLE Project.ProjectTypes (
    ProjectTypeId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TypeName       NVARCHAR(100) NOT NULL,
    Description    NVARCHAR(255) NULL,
    IsActive       BIT NOT NULL DEFAULT ((1)),
    SortOrder      INT NOT NULL DEFAULT ((0)),
    CreatedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.Departments ----------
CREATE TABLE Project.Departments (
    DepartmentId    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DepartmentName  NVARCHAR(100) NOT NULL,
    IsActive        BIT NOT NULL DEFAULT ((1)),
    SortOrder       INT NOT NULL DEFAULT ((0)),
    CreatedDate     DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.TechStackCatalog ----------
CREATE TABLE Project.TechStackCatalog (
    CatalogId     INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OptionGroup   NVARCHAR(20) NOT NULL,   -- TYPE, NAME, LAYER
    OptionValue   NVARCHAR(100) NOT NULL,
    IsActive      BIT NOT NULL DEFAULT ((1)),
    SortOrder     INT NOT NULL DEFAULT ((0)),
    CreatedDate   DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.Projects ----------
CREATE TABLE Project.Projects (
    ProjectId        INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectCode      VARCHAR(20) NOT NULL,
    ProjectName      NVARCHAR(255) NOT NULL,
    Description      NVARCHAR(MAX) NULL,
    ProjectOwnerId   INT NOT NULL,
    DivisionName     NVARCHAR(100) NULL,
    StartDate        DATE NULL,
    EndDate          DATE NULL,
    ActualEndDate    DATE NULL,
    Status           VARCHAR(20) NOT NULL DEFAULT ('PLANNING'),
    Priority         VARCHAR(10) NOT NULL DEFAULT ('MEDIUM'),
    ProgressPercent  DECIMAL(5,2) NOT NULL DEFAULT ((0)),
    Budget           DECIMAL(18,2) NULL,
    IsActive         BIT NOT NULL DEFAULT ((1)),
    CreatedBy        INT NOT NULL,
    CreatedDate      DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate      DATETIMEOFFSET(7) NULL,
    ProjectTypeId    INT NULL,
    RequesterName    NVARCHAR(100) NULL
);
GO

-- ---------- Project.Milestones ----------
CREATE TABLE Project.Milestones (
    MilestoneId    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId      INT NOT NULL,
    MilestoneName  NVARCHAR(255) NOT NULL,
    DueDate        DATE NULL,
    CompletedDate  DATE NULL,
    Status         VARCHAR(20) NOT NULL DEFAULT ('PENDING'),
    SortOrder      INT NOT NULL DEFAULT ((0)),
    CreatedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    OwnerId        INT NULL,
    StartDate      DATE NULL
);
GO

-- ---------- Project.ProjectMembers ----------
CREATE TABLE Project.ProjectMembers (
    ProjectMemberId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId        INT NOT NULL,
    UserId           INT NOT NULL,
    RoleInProject    VARCHAR(20) NOT NULL DEFAULT ('MEMBER'),
    JoinedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    IsActive         BIT NOT NULL DEFAULT ((1))
);
GO

-- ---------- Project.TechStacks ----------
CREATE TABLE Project.TechStacks (
    TechStackId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId    INT NOT NULL,
    StackType    NVARCHAR(50) NOT NULL,
    StackName    NVARCHAR(100) NOT NULL,
    Version      VARCHAR(50) NULL,
    Layer        VARCHAR(20) NOT NULL DEFAULT ('Frontend'),
    SortOrder    INT NOT NULL DEFAULT ((0)),
    CreatedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.ShowcaseItems ----------
CREATE TABLE Project.ShowcaseItems (
    ShowcaseItemId    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId         INT NOT NULL,
    Title             NVARCHAR(255) NOT NULL,
    Description       NVARCHAR(MAX) NULL,
    FlowDescription   NVARCHAR(MAX) NULL,
    ImageUrl          NVARCHAR(500) NULL,
    SortOrder         INT NOT NULL DEFAULT ((0)),
    CreatedBy         INT NOT NULL,
    CreatedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate       DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Testing.TestSuites ----------
CREATE TABLE Testing.TestSuites (
    TestSuiteId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId    INT NOT NULL,
    SuiteCode    VARCHAR(30) NOT NULL,
    Name         NVARCHAR(255) NOT NULL,
    CreatedBy    INT NOT NULL,
    IsActive     BIT NOT NULL DEFAULT ((1)),
    CreatedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate  DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Flow.FlowDefinitions ----------
CREATE TABLE Flow.FlowDefinitions (
    FlowDefinitionId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FlowCode          VARCHAR(30) NOT NULL,
    Name              NVARCHAR(255) NOT NULL,
    Description       NVARCHAR(MAX) NULL,
    Status            VARCHAR(20) NOT NULL DEFAULT ('PLANNING'),
    WorkType          VARCHAR(10) NOT NULL DEFAULT ('SOLO'),
    StartDate         DATE NULL,
    EndDate           DATE NULL,
    ProgressPercent   DECIMAL(5,2) NOT NULL DEFAULT ((0)),
    CreatedBy         INT NOT NULL,
    IsActive          BIT NOT NULL DEFAULT ((1)),
    CreatedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate       DATETIMEOFFSET(7) NULL,
    ProjectId         INT NULL
);
GO

-- ---------- Project.Tasks ----------
CREATE TABLE Project.Tasks (
    TaskId           INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId        INT NOT NULL,
    MilestoneId      INT NULL,
    ParentTaskId     INT NULL,
    TaskName         NVARCHAR(255) NOT NULL,
    Description      NVARCHAR(MAX) NULL,
    Status           VARCHAR(20) NOT NULL DEFAULT ('TODO'),
    Priority         VARCHAR(10) NOT NULL DEFAULT ('MEDIUM'),
    StartDate        DATE NULL,
    DueDate          DATE NULL,
    CompletedDate    DATE NULL,
    ProgressPercent  DECIMAL(5,2) NOT NULL DEFAULT ((0)),
    EstimatedHours   DECIMAL(6,2) NULL,
    CreatedBy        INT NOT NULL,
    CreatedDate      DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate      DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Flow.FlowSteps ----------
CREATE TABLE Flow.FlowSteps (
    FlowStepId        INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FlowDefinitionId  INT NOT NULL,
    StepNo            VARCHAR(20) NOT NULL,
    Title             NVARCHAR(255) NOT NULL,
    Status            VARCHAR(20) NOT NULL DEFAULT ('PENDING'),
    ProgressPercent   INT NOT NULL DEFAULT ((0)),
    StartDate         DATE NULL,
    EndDate           DATE NULL,
    SortOrder         INT NOT NULL DEFAULT ((0)),
    MilestoneId       INT NULL
);
GO

-- ---------- Flow.FlowTechStacks ----------
CREATE TABLE Flow.FlowTechStacks (
    FlowTechStackId   INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FlowDefinitionId  INT NOT NULL,
    Layer             VARCHAR(20) NOT NULL,
    Name              NVARCHAR(100) NOT NULL,
    SortOrder         INT NOT NULL DEFAULT ((0)),
    TechStackId       INT NULL
);
GO

-- ---------- Flow.FlowExecutions ----------
CREATE TABLE Flow.FlowExecutions (
    FlowExecutionId   INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FlowDefinitionId  INT NOT NULL,
    Status            VARCHAR(20) NOT NULL DEFAULT ('RUNNING'),
    StartedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    FinishedDate      DATETIMEOFFSET(7) NULL,
    TriggeredBy       INT NOT NULL,
    Note              NVARCHAR(500) NULL
);
GO

-- ---------- Testing.TestRuns ----------
CREATE TABLE Testing.TestRuns (
    TestRunId        INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TestSuiteId      INT NOT NULL,
    Tool             VARCHAR(20) NOT NULL DEFAULT ('playwright'),
    Environment      VARCHAR(10) NOT NULL DEFAULT ('DEV'),
    RunDate          DATE NOT NULL,
    TotalCases       INT NOT NULL DEFAULT ((0)),
    PassedCases      INT NOT NULL DEFAULT ((0)),
    FailedCases      INT NOT NULL DEFAULT ((0)),
    SkippedCases     INT NOT NULL DEFAULT ((0)),
    DurationSeconds  INT NOT NULL DEFAULT ((0)),
    Status           VARCHAR(10) NOT NULL DEFAULT ('passed'),
    ReportUrl        NVARCHAR(500) NULL,
    Note             NVARCHAR(500) NULL,
    TriggeredBy      INT NOT NULL,
    CreatedDate      DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.TaskAssignees ----------
CREATE TABLE Project.TaskAssignees (
    TaskAssigneeId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TaskId          INT NOT NULL,
    UserId          INT NOT NULL,
    AssignedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.Comments ----------
CREATE TABLE Project.Comments (
    CommentId    BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId    INT NULL,
    TaskId       INT NULL,
    UserId       INT NOT NULL,
    CommentText  NVARCHAR(MAX) NOT NULL,
    CreatedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.Attachments ----------
CREATE TABLE Project.Attachments (
    AttachmentId    BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId       INT NULL,
    TaskId          INT NULL,
    FileName        NVARCHAR(255) NOT NULL,
    FilePath        NVARCHAR(500) NOT NULL,
    FileSizeByte    BIGINT NULL,
    UploadedBy      INT NOT NULL,
    UploadedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.StatusHistory ----------
CREATE TABLE Project.StatusHistory (
    HistoryId    BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId    INT NULL,
    TaskId       INT NULL,
    OldStatus    VARCHAR(20) NULL,
    NewStatus    VARCHAR(20) NOT NULL,
    ChangedBy    INT NOT NULL,
    ChangedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    Remark       NVARCHAR(500) NULL
);
GO

-- ---------- Planning.Events ----------
CREATE TABLE Planning.Events (
    EventId                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId                 INT NOT NULL,
    EventTitle             NVARCHAR(255) NOT NULL,
    Description            NVARCHAR(MAX) NULL,
    EventType              VARCHAR(20) NOT NULL DEFAULT ('APPOINTMENT'),
    StartDateTime          DATETIMEOFFSET(7) NOT NULL,
    EndDateTime            DATETIMEOFFSET(7) NOT NULL,
    IsAllDay               BIT NOT NULL DEFAULT ((0)),
    Location               NVARCHAR(255) NULL,
    ReminderMinutesBefore  INT NULL,
    RecurrenceRule         VARCHAR(100) NULL,
    Status                 VARCHAR(20) NOT NULL DEFAULT ('SCHEDULED'),
    LinkedProjectId        INT NULL,
    LinkedTaskId           INT NULL,
    CreatedDate            DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate            DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Flow.FlowLogs ----------
CREATE TABLE Flow.FlowLogs (
    FlowLogId        BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FlowExecutionId  INT NOT NULL,
    LogLevel         VARCHAR(10) NOT NULL DEFAULT ('INFO'),
    Message          NVARCHAR(MAX) NOT NULL,
    LoggedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Planning.Todos ----------
CREATE TABLE Planning.Todos (
    TodoId         INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId         INT NOT NULL,
    TodoText       NVARCHAR(500) NOT NULL,
    IsCompleted    BIT NOT NULL DEFAULT ((0)),
    CompletedDate  DATETIMEOFFSET(7) NULL,
    DueDate        DATE NULL,
    Priority       VARCHAR(10) NOT NULL DEFAULT ('MEDIUM'),
    SortOrder      INT NOT NULL DEFAULT ((0)),
    LinkedEventId  INT NULL,
    CreatedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate    DATETIMEOFFSET(7) NULL
);
GO

-- =============================================================================
-- SECTION 2 — FOREIGN KEYS (exact names/actions as queried from sys.foreign_keys)
-- =============================================================================

ALTER TABLE Core.Permissions        ADD CONSTRAINT FK_Permissions_System            FOREIGN KEY (SystemId) REFERENCES Core.SystemList(SystemId);
ALTER TABLE Core.Permissions        ADD CONSTRAINT FK_Permissions_Users             FOREIGN KEY (UserId) REFERENCES Core.Users(UserId) ON DELETE CASCADE;

ALTER TABLE Project.Projects        ADD CONSTRAINT FK_Projects_Owner                FOREIGN KEY (ProjectOwnerId) REFERENCES Core.Users(UserId);
ALTER TABLE Project.Projects        ADD CONSTRAINT FK_Projects_Creator              FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);
ALTER TABLE Project.Projects        ADD CONSTRAINT FK_Projects_ProjectType          FOREIGN KEY (ProjectTypeId) REFERENCES Project.ProjectTypes(ProjectTypeId);

ALTER TABLE Project.Milestones      ADD CONSTRAINT FK_Milestones_Project            FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.Milestones      ADD CONSTRAINT FK_Milestones_Owner              FOREIGN KEY (OwnerId) REFERENCES Core.Users(UserId);

ALTER TABLE Project.ProjectMembers  ADD CONSTRAINT FK_ProjectMembers_Project        FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.ProjectMembers  ADD CONSTRAINT FK_ProjectMembers_User           FOREIGN KEY (UserId) REFERENCES Core.Users(UserId);

ALTER TABLE Project.TechStacks      ADD CONSTRAINT FK_TechStacks_Project            FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;

ALTER TABLE Project.ShowcaseItems   ADD CONSTRAINT FK_ShowcaseItems_Project         FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.ShowcaseItems   ADD CONSTRAINT FK_ShowcaseItems_Creator         FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Testing.TestSuites      ADD CONSTRAINT FK_TestSuites_Project            FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Testing.TestSuites      ADD CONSTRAINT FK_TestSuites_Creator            FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Flow.FlowDefinitions    ADD CONSTRAINT FK_FlowDefinitions_Project       FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Flow.FlowDefinitions    ADD CONSTRAINT FK_FlowDefinitions_Creator       FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Project.Tasks           ADD CONSTRAINT FK_Tasks_Project                 FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.Tasks           ADD CONSTRAINT FK_Tasks_Milestone               FOREIGN KEY (MilestoneId) REFERENCES Project.Milestones(MilestoneId);
ALTER TABLE Project.Tasks           ADD CONSTRAINT FK_Tasks_Parent                  FOREIGN KEY (ParentTaskId) REFERENCES Project.Tasks(TaskId);
ALTER TABLE Project.Tasks           ADD CONSTRAINT FK_Tasks_Creator                 FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Flow.FlowSteps          ADD CONSTRAINT FK_FlowSteps_FlowDefinition      FOREIGN KEY (FlowDefinitionId) REFERENCES Flow.FlowDefinitions(FlowDefinitionId) ON DELETE CASCADE;
ALTER TABLE Flow.FlowSteps          ADD CONSTRAINT FK_FlowSteps_Milestone           FOREIGN KEY (MilestoneId) REFERENCES Project.Milestones(MilestoneId);

ALTER TABLE Flow.FlowTechStacks     ADD CONSTRAINT FK_FlowTechStacks_FlowDefinition FOREIGN KEY (FlowDefinitionId) REFERENCES Flow.FlowDefinitions(FlowDefinitionId) ON DELETE CASCADE;
ALTER TABLE Flow.FlowTechStacks     ADD CONSTRAINT FK_FlowTechStacks_TechStack      FOREIGN KEY (TechStackId) REFERENCES Project.TechStacks(TechStackId);

ALTER TABLE Flow.FlowExecutions     ADD CONSTRAINT FK_FlowExecutions_FlowDefinition FOREIGN KEY (FlowDefinitionId) REFERENCES Flow.FlowDefinitions(FlowDefinitionId) ON DELETE CASCADE;
ALTER TABLE Flow.FlowExecutions     ADD CONSTRAINT FK_FlowExecutions_TriggeredBy    FOREIGN KEY (TriggeredBy) REFERENCES Core.Users(UserId);

ALTER TABLE Testing.TestRuns        ADD CONSTRAINT FK_TestRuns_Suite                FOREIGN KEY (TestSuiteId) REFERENCES Testing.TestSuites(TestSuiteId) ON DELETE CASCADE;
ALTER TABLE Testing.TestRuns        ADD CONSTRAINT FK_TestRuns_TriggeredBy          FOREIGN KEY (TriggeredBy) REFERENCES Core.Users(UserId);

ALTER TABLE Project.TaskAssignees   ADD CONSTRAINT FK_TaskAssignees_Task            FOREIGN KEY (TaskId) REFERENCES Project.Tasks(TaskId) ON DELETE CASCADE;
ALTER TABLE Project.TaskAssignees   ADD CONSTRAINT FK_TaskAssignees_User            FOREIGN KEY (UserId) REFERENCES Core.Users(UserId);

ALTER TABLE Project.Comments        ADD CONSTRAINT FK_Comments_Project              FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.Comments        ADD CONSTRAINT FK_Comments_Task                 FOREIGN KEY (TaskId) REFERENCES Project.Tasks(TaskId);
ALTER TABLE Project.Comments        ADD CONSTRAINT FK_Comments_User                 FOREIGN KEY (UserId) REFERENCES Core.Users(UserId);

ALTER TABLE Project.Attachments     ADD CONSTRAINT FK_Attachments_Project           FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.Attachments     ADD CONSTRAINT FK_Attachments_Task              FOREIGN KEY (TaskId) REFERENCES Project.Tasks(TaskId);
ALTER TABLE Project.Attachments     ADD CONSTRAINT FK_Attachments_Uploader          FOREIGN KEY (UploadedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Project.StatusHistory   ADD CONSTRAINT FK_StatusHistory_Project         FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId);
ALTER TABLE Project.StatusHistory   ADD CONSTRAINT FK_StatusHistory_Task            FOREIGN KEY (TaskId) REFERENCES Project.Tasks(TaskId);
ALTER TABLE Project.StatusHistory   ADD CONSTRAINT FK_StatusHistory_User            FOREIGN KEY (ChangedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Planning.Events         ADD CONSTRAINT FK_Events_User                   FOREIGN KEY (UserId) REFERENCES Core.Users(UserId);
ALTER TABLE Planning.Events         ADD CONSTRAINT FK_Events_Project                FOREIGN KEY (LinkedProjectId) REFERENCES Project.Projects(ProjectId);
ALTER TABLE Planning.Events         ADD CONSTRAINT FK_Events_Task                   FOREIGN KEY (LinkedTaskId) REFERENCES Project.Tasks(TaskId);

ALTER TABLE Flow.FlowLogs           ADD CONSTRAINT FK_FlowLogs_Execution            FOREIGN KEY (FlowExecutionId) REFERENCES Flow.FlowExecutions(FlowExecutionId) ON DELETE CASCADE;

ALTER TABLE Planning.Todos          ADD CONSTRAINT FK_Todos_User                    FOREIGN KEY (UserId) REFERENCES Core.Users(UserId);
ALTER TABLE Planning.Todos          ADD CONSTRAINT FK_Todos_Event                   FOREIGN KEY (LinkedEventId) REFERENCES Planning.Events(EventId);
GO

-- =============================================================================
-- SECTION 3 — UNIQUE CONSTRAINTS / UNIQUE INDEXES (exact names as queried)
-- =============================================================================

ALTER TABLE Core.Permissions        ADD CONSTRAINT UQ_User_System UNIQUE (UserId, SystemId);
ALTER TABLE Core.Users              ADD CONSTRAINT [UQ__Users__AF2DBB988DFB40A8] UNIQUE (EmpId);
ALTER TABLE Flow.FlowDefinitions    ADD CONSTRAINT UQ_FlowDefinitions_FlowCode UNIQUE (FlowCode);
ALTER TABLE Project.ProjectMembers  ADD CONSTRAINT UQ_Project_User UNIQUE (ProjectId, UserId);
ALTER TABLE Project.Projects        ADD CONSTRAINT [UQ__Projects__2F3A4948DB4CB711] UNIQUE (ProjectCode);
ALTER TABLE Project.ProjectTypes    ADD CONSTRAINT [UQ__ProjectT__D4E7DFA8BD8ADE64] UNIQUE (TypeName);
ALTER TABLE Project.TaskAssignees   ADD CONSTRAINT UQ_Task_User UNIQUE (TaskId, UserId);
ALTER TABLE Testing.TestSuites      ADD CONSTRAINT UQ_TestSuites_SuiteCode UNIQUE (SuiteCode);
GO

-- Nullable-FK unique index (SQL Server treats multiple NULLs as distinct, so this
-- still allows unlinked Flow rows while enforcing 1:1 for linked ones)
CREATE UNIQUE INDEX UQ_FlowDefinitions_ProjectId ON Flow.FlowDefinitions(ProjectId);
GO

-- =============================================================================
-- SECTION 4 — NON-UNIQUE INDEXES (exact names/columns as queried)
-- =============================================================================

CREATE INDEX IX_AuditLogs_LogDate ON Core.AuditLogs(LogDate);
CREATE INDEX IX_AuditLogs_User_System ON Core.AuditLogs(UserId, SystemId);
CREATE INDEX IX_Permissions_User_System ON Core.Permissions(UserId, SystemId);
CREATE INDEX IX_Users_EmpId ON Core.Users(EmpId);
CREATE INDEX IX_Users_LoginStatus ON Core.Users(IsActive, IsSuspended, IsOnline);

CREATE INDEX IX_Events_User_Range ON Planning.Events(UserId, StartDateTime, EndDateTime);
CREATE INDEX IX_Todos_User_Status ON Planning.Todos(UserId, IsCompleted, DueDate);

CREATE INDEX IX_Attachments_Project ON Project.Attachments(ProjectId);
CREATE INDEX IX_Attachments_Task ON Project.Attachments(TaskId);
CREATE INDEX IX_Comments_Project ON Project.Comments(ProjectId);
CREATE INDEX IX_Comments_Task ON Project.Comments(TaskId);
CREATE INDEX IX_Milestones_Owner ON Project.Milestones(OwnerId);
CREATE INDEX IX_Milestones_Project ON Project.Milestones(ProjectId, DueDate);
CREATE INDEX IX_ProjectMembers_User ON Project.ProjectMembers(UserId);
CREATE INDEX IX_Projects_Owner ON Project.Projects(ProjectOwnerId);
CREATE INDEX IX_Projects_ProjectType ON Project.Projects(ProjectTypeId);
CREATE INDEX IX_Projects_Status ON Project.Projects(Status, IsActive);
CREATE INDEX IX_ShowcaseItems_Project ON Project.ShowcaseItems(ProjectId);
CREATE INDEX IX_StatusHistory_Project ON Project.StatusHistory(ProjectId, ChangedDate);
CREATE INDEX IX_StatusHistory_Task ON Project.StatusHistory(TaskId, ChangedDate);
CREATE INDEX IX_TaskAssignees_User ON Project.TaskAssignees(UserId);
CREATE INDEX IX_Tasks_DueDate ON Project.Tasks(DueDate);
CREATE INDEX IX_Tasks_Milestone ON Project.Tasks(MilestoneId);
CREATE INDEX IX_Tasks_Project_Status ON Project.Tasks(ProjectId, Status);
CREATE INDEX IX_TechStacks_Project ON Project.TechStacks(ProjectId);
GO

-- =============================================================================
-- SECTION 5 — CHECK CONSTRAINTS (exact names/definitions as queried)
-- =============================================================================

ALTER TABLE Flow.FlowDefinitions  ADD CONSTRAINT CK_FlowDefinitions_Status CHECK ([Status]='COMPLETED' OR [Status]='IN_PROGRESS' OR [Status]='PLANNING');
ALTER TABLE Flow.FlowDefinitions  ADD CONSTRAINT CK_FlowDefinitions_WorkType CHECK ([WorkType]='TEAM' OR [WorkType]='SOLO');
ALTER TABLE Flow.FlowExecutions   ADD CONSTRAINT CK_FlowExecutions_Status CHECK ([Status]='FAILED' OR [Status]='SUCCESS' OR [Status]='RUNNING');
ALTER TABLE Flow.FlowLogs         ADD CONSTRAINT CK_FlowLogs_Level CHECK ([LogLevel]='ERROR' OR [LogLevel]='WARN' OR [LogLevel]='INFO');
ALTER TABLE Flow.FlowSteps        ADD CONSTRAINT CK_FlowSteps_Status CHECK ([Status]='DONE' OR [Status]='IN_PROGRESS' OR [Status]='PENDING');
ALTER TABLE Flow.FlowSteps        ADD CONSTRAINT CK_FlowSteps_Progress CHECK ([ProgressPercent]>=(0) AND [ProgressPercent]<=(100));
ALTER TABLE Flow.FlowTechStacks   ADD CONSTRAINT CK_FlowTechStacks_Layer CHECK ([Layer]='DATABASE' OR [Layer]='BACKEND' OR [Layer]='FRONTEND');
ALTER TABLE Planning.Events       ADD CONSTRAINT CK_Events_DateRange CHECK ([EndDateTime]>=[StartDateTime]);
ALTER TABLE Project.Attachments   ADD CONSTRAINT CK_Attachments_RefTarget CHECK ([ProjectId] IS NOT NULL OR [TaskId] IS NOT NULL);
ALTER TABLE Project.Comments      ADD CONSTRAINT CK_Comments_RefTarget CHECK ([ProjectId] IS NOT NULL OR [TaskId] IS NOT NULL);
ALTER TABLE Testing.TestRuns      ADD CONSTRAINT CK_TestRuns_Tool CHECK ([Tool]='robot' OR [Tool]='jest' OR [Tool]='vitest' OR [Tool]='cypress' OR [Tool]='playwright');
ALTER TABLE Testing.TestRuns      ADD CONSTRAINT CK_TestRuns_Environment CHECK ([Environment]='PROD' OR [Environment]='UAT' OR [Environment]='SIT' OR [Environment]='DEV');
ALTER TABLE Testing.TestRuns      ADD CONSTRAINT CK_TestRuns_Status CHECK ([Status]='skipped' OR [Status]='partial' OR [Status]='failed' OR [Status]='passed');
GO

-- =============================================================================
-- SECTION 6 — MASTER / LOOKUP SEED DATA (real current rows from the live DB)
-- =============================================================================

-- Core.SystemList — module registry (Permissions.SystemId FKs into this)
SET IDENTITY_INSERT Core.SystemList ON;
INSERT INTO Core.SystemList (SystemId, SystemName, Description, IsActive) VALUES
    (N'CORE',     N'Core Management',            N'ระบบบริหารจัดการหลัก สิทธิ์ และความปลอดภัย', 1),
    (N'PLANNING', N'งานเดี่ยว (Solo)',           N'ระบบวางแผนงานเดี่ยว — บริหารจัดการโปรเจกต์ที่ทำคนเดียว', 1),
    (N'PROJECT',  N'งานทีม (Team)',              N'ระบบติดตามงานโปรเจกต์ทีม — บริหารจัดการโปรเจกต์ที่ทำร่วมกับทีม', 1),
    (N'SOLO',     N'Project Solo Management',    N'ระบบบริหารจัดการโปรเจกต์เดี่ยว', 1),
    (N'TEAM',     N'Project Team Management',    N'ระบบบริหารจัดการโปรเจกต์ทีม', 1),
    (N'FLOW',     N'Project Flow Architecture',  N'ระบบออกแบบและติดตามผังการทำงานของโปรเจกต์', 1);
SET IDENTITY_INSERT Core.SystemList OFF;
GO

-- Project.ProjectTypes — project-type templates used by AutoGeneratePhasesAsync
SET IDENTITY_INSERT Project.ProjectTypes ON;
INSERT INTO Project.ProjectTypes (ProjectTypeId, TypeName, Description, IsActive, SortOrder) VALUES
    (1, N'Web Application',     NULL, 1, 1),
    (2, N'Mobile Application',  NULL, 1, 2),
    (3, N'API / Microservice',  NULL, 1, 3),
    (4, N'Desktop Application', NULL, 1, 4);
SET IDENTITY_INSERT Project.ProjectTypes OFF;
GO

-- Project.Departments — "หน่วยงาน" dropdown master data
SET IDENTITY_INSERT Project.Departments ON;
INSERT INTO Project.Departments (DepartmentId, DepartmentName, IsActive, SortOrder) VALUES
    (1, N'ระบบดิจิตอลและIT', 1, 1),
    (2, N'ฝ่ายซ่อมบำรุง', 1, 2),
    (3, N'ฝ่ายคลังสินค้าและจัดส่ง', 1, 3),
    (4, N'ฝ่ายทรัพยากรบุคคล', 1, 4);
SET IDENTITY_INSERT Project.Departments OFF;
GO

-- Project.TechStackCatalog — Stack "ประเภท/ชื่อ/Layer" dropdown master data (3 independent option groups)
SET IDENTITY_INSERT Project.TechStackCatalog ON;
INSERT INTO Project.TechStackCatalog (CatalogId, OptionGroup, OptionValue, IsActive, SortOrder) VALUES
    (1,  N'TYPE',  N'ภาษา (Language)',    1, 1),
    (2,  N'TYPE',  N'Framework',          1, 2),
    (3,  N'TYPE',  N'Library / Package',  1, 3),
    (4,  N'TYPE',  N'Database',           1, 4),
    (5,  N'NAME',  N'Next.js',            1, 1),
    (6,  N'NAME',  N'React',              1, 2),
    (7,  N'NAME',  N'TypeScript',         1, 3),
    (8,  N'NAME',  N'ASP.NET Core',       1, 4),
    (9,  N'NAME',  N'SQL Server',         1, 5),
    (10, N'NAME',  N'Tailwind CSS',       1, 6),
    (11, N'NAME',  N'Zustand',            1, 7),
    (12, N'NAME',  N'Docker',             1, 8),
    (13, N'LAYER', N'Frontend',           1, 1),
    (14, N'LAYER', N'Backend',            1, 2),
    (15, N'LAYER', N'Database',           1, 3),
    (16, N'LAYER', N'DevOps',             1, 4);
SET IDENTITY_INSERT Project.TechStackCatalog OFF;
GO
