-- =============================================================================
-- DatabaseBackup_ProjectDevHub.sql
-- Full schema + master/lookup seed data export of the ProjectDevHub SQL Server
-- database, generated by querying sys.tables/sys.columns/sys.foreign_keys/
-- sys.indexes/sys.check_constraints/sys.identity_columns/sys.default_constraints
-- directly against the live database (server DESKTOP-TJ7525D\SQLEXPRESS,
-- database ProjectDevHub) — not derived/guessed from the C# model code.
--
-- Table order below follows FK dependency (parent tables before child tables),
-- verified against the real sys.foreign_keys graph.
--
-- Note: while extracting this backup, three master/lookup tables were found to
-- have mojibake-corrupted Thai text (Core.SystemList rows SOLO/TEAM/FLOW,
-- Project.Departments all 4 rows, Project.TechStackCatalog CatalogId=1) caused
-- by an earlier session running an UPDATE/INSERT script through sqlcmd without
-- specifying a UTF-8 codepage. Those values were corrected in the live database
-- (via a parameterized ADO.NET UPDATE, bypassing console codepage entirely)
-- before this export was taken, so the seed data below reflects the corrected,
-- intended text. A full sweep of every nvarchar/nchar column in every table
-- confirmed no other rows were affected.
--
-- ⚠ UTF-8 / Thai Text Safety — ต้องระบุ Codepage ทุกครั้งที่รัน ⚠
-- sqlcmd อ่านไฟล์สคริปต์นี้ด้วย Codepage เริ่มต้นของเครื่อง (ไม่ใช่ UTF-8) เว้นแต่จะสั่งชัดเจนด้วย -f 65001
-- ถ้าลืม Flag นี้ ข้อความไทยทุกจุดใน Seed Data ด้านล่าง (SystemList/Departments/TechStackCatalog/ผู้ดูแลระบบ)
-- จะถูกอ่านผิด Codepage แล้ว Insert เป็นตัวอักษรมั่ว (Mojibake) ทันที — เคยเกิดเหตุการณ์นี้มาแล้ว 2 ครั้ง
-- (รอบแรก: SOLO/TEAM/FLOW/Departments/TechStackCatalog, รอบสอง: แถว PRESENT ที่เพิ่มเข้ามาทีหลัง)
--
-- สคริปต์นี้ออกแบบไว้สำหรับ "สร้างฐานข้อมูลใหม่ทั้งก้อน" เท่านั้น (CREATE TABLE ด้านล่างไม่ได้ Guard ด้วย
-- IF NOT EXISTS) — ถ้าฐานข้อมูล ProjectDevHub มีอยู่แล้วและมี Schema ครบ ให้ DROP DATABASE ProjectDevHub
-- ทิ้งก่อน (หรือใช้ชื่อฐานข้อมูลใหม่) แล้วค่อยรันสคริปต์นี้ ไม่เช่นนั้นจะเจอ Error "There is already an
-- object named ... in the database" ที่ CREATE TABLE ตัวแรกที่ชนกัน
--
-- Restore แบบสร้างฐานข้อมูลใหม่ทั้งก้อน (เชื่อมต่อไปที่ master ก่อน เพราะฐานข้อมูล ProjectDevHub ยังไม่มีอยู่จริง —
-- สคริปต์จะ CREATE DATABASE ให้เองที่บรรทัดถัดไป แล้ว USE เข้าไปสร้าง Schema/Table/Seed Data ต่ออัตโนมัติ):
--   sqlcmd -S "DESKTOP-TJ7525D\SQLEXPRESS" -U sa -P 1234 -C -d master -f 65001 -i DatabaseBackup_ProjectDevHub.sql
--
-- Default Admin สำหรับ Login ครั้งแรกหลัง Restore (Seed ไว้ใน Section 6):
--   EmpId: ADMIN   Password: Admin@123   (แนะนำให้เปลี่ยนรหัสผ่านทันทีหลังใช้งานจริง)
--
-- Section index: 1) Tables  2) Foreign Keys  3) Unique Constraints/Indexes
-- 4) Non-Unique Indexes  5) Check Constraints  6) Master/Lookup Seed Data
-- 7) Views  8) Stored Procedures  9) Triggers (ครบทุก DB Object ที่มีอยู่จริงบน Live DB
-- ณ วันที่ Export — รันสคริปต์นี้ตัวเดียวสร้างฐานข้อมูลใหม่ได้ครบทุกอย่างโดยไม่ต้องพึ่งขั้นตอนอื่น)
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'ProjectDevHub')
BEGIN
    CREATE DATABASE ProjectDevHub;
END
GO

USE ProjectDevHub;
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Core')     EXEC('CREATE SCHEMA Core');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Project')  EXEC('CREATE SCHEMA Project');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Flow')     EXEC('CREATE SCHEMA Flow');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Testing')  EXEC('CREATE SCHEMA Testing');
GO

-- =============================================================================
-- SECTION 1 — CREATE TABLE (ordered so every FK's parent table already exists)
-- =============================================================================

-- ---------- Core.Users ----------
CREATE TABLE Core.Users (
    UserId              INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    EmpId               VARCHAR(20)  NOT NULL,
    PasswordHash        VARCHAR(255) NOT NULL,
    FullName            NVARCHAR(100) NOT NULL,
    DivisionName        NVARCHAR(100) NULL,
    DepartmentName      NVARCHAR(100) NULL,
    SectionName         NVARCHAR(100) NULL,
    UserLevel           INT NOT NULL DEFAULT ((1)),
    IsSuperAdmin        BIT NOT NULL DEFAULT ((0)),
    IsSuspended         BIT NOT NULL DEFAULT ((0)),
    IsOnline            BIT NOT NULL DEFAULT ((0)),
    CurrentSessionId    VARCHAR(100) NULL,
    ComputerName        VARCHAR(255) NULL,
    IpAddress           VARCHAR(45)  NULL,
    LastLoginDate       DATETIMEOFFSET(7) NULL,
    IsActive            BIT NOT NULL DEFAULT ((1)),
    CreatedDate         DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate         DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Core.SystemList ----------
CREATE TABLE Core.SystemList (
    SystemId     VARCHAR(50) NOT NULL PRIMARY KEY,
    SystemName   NVARCHAR(100) NOT NULL,
    Description  NVARCHAR(255) NULL,
    IsActive     BIT NOT NULL DEFAULT ((1)),
    CreatedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Core.Permissions ----------
CREATE TABLE Core.Permissions (
    PermissionId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId        INT NOT NULL,
    SystemId      VARCHAR(50) NOT NULL,
    CanView       BIT NOT NULL DEFAULT ((0)),
    CanAdd        BIT NOT NULL DEFAULT ((0)),
    CanEdit       BIT NOT NULL DEFAULT ((0)),
    CanDelete     BIT NOT NULL DEFAULT ((0)),
    CanApprove    BIT NOT NULL DEFAULT ((0)),
    CanReject     BIT NOT NULL DEFAULT ((0)),
    CreatedDate   DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate   DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Core.AuditLogs ----------
CREATE TABLE Core.AuditLogs (
    LogId            BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId           INT NULL,
    SystemId         VARCHAR(50) NOT NULL,
    ActionType       VARCHAR(50) NOT NULL,
    LogDescription   NVARCHAR(MAX) NULL,
    LogRef           NVARCHAR(100) NULL,
    IpAddress        VARCHAR(45) NULL,
    ComputerName     VARCHAR(255) NULL,
    LogDate          DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.ProjectTypes ----------
CREATE TABLE Project.ProjectTypes (
    ProjectTypeId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TypeName       NVARCHAR(100) NOT NULL,
    Description    NVARCHAR(255) NULL,
    IsActive       BIT NOT NULL DEFAULT ((1)),
    SortOrder      INT NOT NULL DEFAULT ((0)),
    CreatedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.Departments ----------
CREATE TABLE Project.Departments (
    DepartmentId    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DepartmentName  NVARCHAR(100) NOT NULL,
    IsActive        BIT NOT NULL DEFAULT ((1)),
    SortOrder       INT NOT NULL DEFAULT ((0)),
    CreatedDate     DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.TechStackCatalog ----------
CREATE TABLE Project.TechStackCatalog (
    CatalogId     INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OptionGroup   NVARCHAR(20) NOT NULL,   -- TYPE, NAME, LAYER
    OptionValue   NVARCHAR(100) NOT NULL,
    TypeId        INT NULL,                -- มีความหมายเฉพาะแถว OptionGroup='NAME' — Self-Ref ชี้กลับไปแถว TYPE ต้นทาง (CatalogId)
    IsActive      BIT NOT NULL DEFAULT ((1)),
    SortOrder     INT NOT NULL DEFAULT ((0)),
    CreatedDate   DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.Projects ----------
CREATE TABLE Project.Projects (
    ProjectId        INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectCode      VARCHAR(20) NOT NULL,
    ProjectName      NVARCHAR(255) NOT NULL,
    Description      NVARCHAR(MAX) NULL,
    ProjectOwnerId   INT NOT NULL,
    DivisionName     NVARCHAR(100) NULL,
    StartDate        DATE NULL,
    EndDate          DATE NULL,
    ActualEndDate    DATE NULL,
    Status           VARCHAR(20) NOT NULL DEFAULT ('PLANNING'),
    Priority         VARCHAR(10) NOT NULL DEFAULT ('MEDIUM'),
    ProgressPercent  DECIMAL(5,2) NOT NULL DEFAULT ((0)),
    Budget           DECIMAL(18,2) NULL,
    IsActive         BIT NOT NULL DEFAULT ((1)),
    CreatedBy        INT NOT NULL,
    CreatedDate      DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate      DATETIMEOFFSET(7) NULL,
    ProjectTypeId    INT NULL,
    RequesterName    NVARCHAR(100) NULL,
    -- Denormalize จาก Core.Users(EmpId, FullName) ผ่าน Trigger — ให้เปิดตารางนี้ตรงๆ แล้วรู้ทันทีว่าโปรเจกต์เป็นของใคร
    OwnerEmpId       VARCHAR(20) NULL,
    OwnerName        NVARCHAR(255) NULL
);
GO

-- ---------- Project.Milestones ----------
CREATE TABLE Project.Milestones (
    MilestoneId    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId      INT NOT NULL,
    MilestoneName  NVARCHAR(255) NOT NULL,
    DueDate        DATE NULL,
    CompletedDate  DATE NULL,
    Status         VARCHAR(20) NOT NULL DEFAULT ('PENDING'),
    SortOrder      INT NOT NULL DEFAULT ((0)),
    CreatedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    OwnerId        INT NULL,
    StartDate      DATE NULL
);
GO

-- ---------- Project.ProjectMembers ----------
CREATE TABLE Project.ProjectMembers (
    ProjectMemberId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId        INT NOT NULL,
    UserId           INT NOT NULL,
    RoleInProject    VARCHAR(20) NOT NULL DEFAULT ('MEMBER'),
    JoinedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    IsActive         BIT NOT NULL DEFAULT ((1))
);
GO

-- ---------- Project.TechStacks ----------
CREATE TABLE Project.TechStacks (
    TechStackId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId    INT NOT NULL,
    StackType    NVARCHAR(50) NOT NULL,
    StackName    NVARCHAR(100) NOT NULL,
    Version      VARCHAR(50) NULL,
    Layer        VARCHAR(20) NOT NULL DEFAULT ('Frontend'),
    SortOrder    INT NOT NULL DEFAULT ((0)),
    CreatedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.ShowcaseItems ----------
CREATE TABLE Project.ShowcaseItems (
    ShowcaseItemId    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId         INT NOT NULL,
    Title             NVARCHAR(255) NOT NULL,
    Description       NVARCHAR(MAX) NULL,
    FlowDescription   NVARCHAR(MAX) NULL,
    ImageUrl          NVARCHAR(500) NULL,
    SortOrder         INT NOT NULL DEFAULT ((0)),
    CreatedBy         INT NOT NULL,
    CreatedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate       DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Testing.TestSuites ----------
CREATE TABLE Testing.TestSuites (
    TestSuiteId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId    INT NOT NULL,
    SuiteCode    VARCHAR(30) NOT NULL,
    Name         NVARCHAR(255) NOT NULL,
    CreatedBy    INT NOT NULL,
    IsActive     BIT NOT NULL DEFAULT ((1)),
    CreatedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate  DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Flow.FlowDefinitions ----------
CREATE TABLE Flow.FlowDefinitions (
    FlowDefinitionId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FlowCode          VARCHAR(30) NOT NULL,
    Name              NVARCHAR(255) NOT NULL,
    Description       NVARCHAR(MAX) NULL,
    Status            VARCHAR(20) NOT NULL DEFAULT ('PLANNING'),
    WorkType          VARCHAR(10) NOT NULL DEFAULT ('SOLO'),
    StartDate         DATE NULL,
    EndDate           DATE NULL,
    ProgressPercent   DECIMAL(5,2) NOT NULL DEFAULT ((0)),
    SystemType        NVARCHAR(255) NULL,
    ModuleList        NVARCHAR(500) NULL,
    DfdLevel          VARCHAR(10) NOT NULL DEFAULT ('level0'),
    CreatedBy         INT NOT NULL,
    IsActive          BIT NOT NULL DEFAULT ((1)),
    CreatedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate       DATETIMEOFFSET(7) NULL,
    ProjectId         INT NULL
);
GO

-- ---------- Project.Tasks ----------
CREATE TABLE Project.Tasks (
    TaskId           INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId        INT NOT NULL,
    MilestoneId      INT NULL,
    ParentTaskId     INT NULL,
    TaskName         NVARCHAR(255) NOT NULL,
    Description      NVARCHAR(MAX) NULL,
    Status           VARCHAR(20) NOT NULL DEFAULT ('TODO'),
    Priority         VARCHAR(10) NOT NULL DEFAULT ('MEDIUM'),
    StartDate        DATE NULL,
    DueDate          DATE NULL,
    CompletedDate    DATE NULL,
    ProgressPercent  DECIMAL(5,2) NOT NULL DEFAULT ((0)),
    EstimatedHours   DECIMAL(6,2) NULL,
    CreatedBy        INT NOT NULL,
    CreatedDate      DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    UpdatedDate      DATETIMEOFFSET(7) NULL
);
GO

-- ---------- Testing.TestRuns ----------
CREATE TABLE Testing.TestRuns (
    TestRunId        INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TestSuiteId      INT NOT NULL,
    Tool             VARCHAR(20) NOT NULL DEFAULT ('playwright'),
    Environment      VARCHAR(10) NOT NULL DEFAULT ('DEV'),
    RunDate          DATE NOT NULL,
    TotalCases       INT NOT NULL DEFAULT ((0)),
    PassedCases      INT NOT NULL DEFAULT ((0)),
    FailedCases      INT NOT NULL DEFAULT ((0)),
    SkippedCases     INT NOT NULL DEFAULT ((0)),
    DurationSeconds  INT NOT NULL DEFAULT ((0)),
    Status           VARCHAR(10) NOT NULL DEFAULT ('passed'),
    ReportUrl        NVARCHAR(500) NULL,
    Note             NVARCHAR(500) NULL,
    TriggeredBy      INT NOT NULL,
    CreatedDate      DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.TaskAssignees ----------
CREATE TABLE Project.TaskAssignees (
    TaskAssigneeId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TaskId          INT NOT NULL,
    UserId          INT NOT NULL,
    AssignedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.Comments ----------
CREATE TABLE Project.Comments (
    CommentId    BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId    INT NULL,
    TaskId       INT NULL,
    UserId       INT NOT NULL,
    CommentText  NVARCHAR(MAX) NOT NULL,
    CreatedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.Attachments ----------
CREATE TABLE Project.Attachments (
    AttachmentId    BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId       INT NULL,
    TaskId          INT NULL,
    FileName        NVARCHAR(255) NOT NULL,
    FilePath        NVARCHAR(500) NOT NULL,
    FileSizeByte    BIGINT NULL,
    UploadedBy      INT NOT NULL,
    UploadedDate    DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- ---------- Project.StatusHistory ----------
CREATE TABLE Project.StatusHistory (
    HistoryId    BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProjectId    INT NULL,
    TaskId       INT NULL,
    OldStatus    VARCHAR(20) NULL,
    NewStatus    VARCHAR(20) NOT NULL,
    ChangedBy    INT NOT NULL,
    ChangedDate  DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset()),
    Remark       NVARCHAR(500) NULL
);
GO

-- ---------- Flow.FlowDiagramRows (Workflow Diagram Studio — พอร์ตมาจาก AutoFlowStudio_ModulesD) ----------
CREATE TABLE Flow.FlowDiagramRows (
    FlowDiagramRowId  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FlowDefinitionId  INT NOT NULL,
    DiagramType       VARCHAR(20) NOT NULL,  -- FLOWCHART, USECASE, DFD, SEQUENCE, ERD, STATE
    StepNo            NVARCHAR(20) NULL,
    Actor             NVARCHAR(200) NULL,
    Action            NVARCHAR(500) NULL,
    DataField         NVARCHAR(300) NULL,
    Decision          NVARCHAR(300) NULL,
    NextStep          NVARCHAR(100) NULL,
    OptionValue       NVARCHAR(100) NULL,
    SortOrder         INT NOT NULL DEFAULT ((0)),
    CreatedDate       DATETIMEOFFSET(7) NOT NULL DEFAULT (sysdatetimeoffset())
);
GO

-- =============================================================================
-- SECTION 2 — FOREIGN KEYS (exact names/actions as queried from sys.foreign_keys)
-- =============================================================================

ALTER TABLE Core.Permissions        ADD CONSTRAINT FK_Permissions_System            FOREIGN KEY (SystemId) REFERENCES Core.SystemList(SystemId);
ALTER TABLE Core.Permissions        ADD CONSTRAINT FK_Permissions_Users             FOREIGN KEY (UserId) REFERENCES Core.Users(UserId) ON DELETE CASCADE;

ALTER TABLE Project.Projects        ADD CONSTRAINT FK_Projects_Owner                FOREIGN KEY (ProjectOwnerId) REFERENCES Core.Users(UserId);
ALTER TABLE Project.Projects        ADD CONSTRAINT FK_Projects_Creator              FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);
ALTER TABLE Project.Projects        ADD CONSTRAINT FK_Projects_ProjectType          FOREIGN KEY (ProjectTypeId) REFERENCES Project.ProjectTypes(ProjectTypeId);

ALTER TABLE Project.Milestones      ADD CONSTRAINT FK_Milestones_Project            FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.Milestones      ADD CONSTRAINT FK_Milestones_Owner              FOREIGN KEY (OwnerId) REFERENCES Core.Users(UserId);

ALTER TABLE Project.ProjectMembers  ADD CONSTRAINT FK_ProjectMembers_Project        FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
-- Phase 5: Cascade เมื่อลบ User — ProjectMembers เป็นแค่ความสัมพันธ์ "เป็นสมาชิกของ" ไม่ใช่ข้อมูลที่ User เป็นเจ้าของ
ALTER TABLE Project.ProjectMembers  ADD CONSTRAINT FK_ProjectMembers_User           FOREIGN KEY (UserId) REFERENCES Core.Users(UserId) ON DELETE CASCADE;

ALTER TABLE Project.TechStacks      ADD CONSTRAINT FK_TechStacks_Project            FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;

ALTER TABLE Project.TechStackCatalog ADD CONSTRAINT FK_TechStackCatalog_Type        FOREIGN KEY (TypeId) REFERENCES Project.TechStackCatalog(CatalogId);

ALTER TABLE Project.ShowcaseItems   ADD CONSTRAINT FK_ShowcaseItems_Project         FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.ShowcaseItems   ADD CONSTRAINT FK_ShowcaseItems_Creator         FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Testing.TestSuites      ADD CONSTRAINT FK_TestSuites_Project            FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Testing.TestSuites      ADD CONSTRAINT FK_TestSuites_Creator            FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Flow.FlowDefinitions    ADD CONSTRAINT FK_FlowDefinitions_Project       FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Flow.FlowDefinitions    ADD CONSTRAINT FK_FlowDefinitions_Creator       FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Project.Tasks           ADD CONSTRAINT FK_Tasks_Project                 FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.Tasks           ADD CONSTRAINT FK_Tasks_Milestone               FOREIGN KEY (MilestoneId) REFERENCES Project.Milestones(MilestoneId);
ALTER TABLE Project.Tasks           ADD CONSTRAINT FK_Tasks_Parent                  FOREIGN KEY (ParentTaskId) REFERENCES Project.Tasks(TaskId);
ALTER TABLE Project.Tasks           ADD CONSTRAINT FK_Tasks_Creator                 FOREIGN KEY (CreatedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Testing.TestRuns        ADD CONSTRAINT FK_TestRuns_Suite                FOREIGN KEY (TestSuiteId) REFERENCES Testing.TestSuites(TestSuiteId) ON DELETE CASCADE;
ALTER TABLE Testing.TestRuns        ADD CONSTRAINT FK_TestRuns_TriggeredBy          FOREIGN KEY (TriggeredBy) REFERENCES Core.Users(UserId);

ALTER TABLE Project.TaskAssignees   ADD CONSTRAINT FK_TaskAssignees_Task            FOREIGN KEY (TaskId) REFERENCES Project.Tasks(TaskId) ON DELETE CASCADE;
-- Phase 5: Cascade เมื่อลบ User — TaskAssignees เป็นแค่ความสัมพันธ์ "ถูกมอบหมายงาน" ไม่ใช่ข้อมูลที่ User เป็นเจ้าของ
ALTER TABLE Project.TaskAssignees   ADD CONSTRAINT FK_TaskAssignees_User            FOREIGN KEY (UserId) REFERENCES Core.Users(UserId) ON DELETE CASCADE;

ALTER TABLE Project.Comments        ADD CONSTRAINT FK_Comments_Project              FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.Comments        ADD CONSTRAINT FK_Comments_Task                 FOREIGN KEY (TaskId) REFERENCES Project.Tasks(TaskId);
ALTER TABLE Project.Comments        ADD CONSTRAINT FK_Comments_User                 FOREIGN KEY (UserId) REFERENCES Core.Users(UserId);

ALTER TABLE Project.Attachments     ADD CONSTRAINT FK_Attachments_Project           FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId) ON DELETE CASCADE;
ALTER TABLE Project.Attachments     ADD CONSTRAINT FK_Attachments_Task              FOREIGN KEY (TaskId) REFERENCES Project.Tasks(TaskId);
ALTER TABLE Project.Attachments     ADD CONSTRAINT FK_Attachments_Uploader          FOREIGN KEY (UploadedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Project.StatusHistory   ADD CONSTRAINT FK_StatusHistory_Project         FOREIGN KEY (ProjectId) REFERENCES Project.Projects(ProjectId);
ALTER TABLE Project.StatusHistory   ADD CONSTRAINT FK_StatusHistory_Task            FOREIGN KEY (TaskId) REFERENCES Project.Tasks(TaskId);
ALTER TABLE Project.StatusHistory   ADD CONSTRAINT FK_StatusHistory_User            FOREIGN KEY (ChangedBy) REFERENCES Core.Users(UserId);

ALTER TABLE Flow.FlowDiagramRows    ADD CONSTRAINT FK_FlowDiagramRows_FlowDefinition FOREIGN KEY (FlowDefinitionId) REFERENCES Flow.FlowDefinitions(FlowDefinitionId) ON DELETE CASCADE;
GO

-- =============================================================================
-- SECTION 3 — UNIQUE CONSTRAINTS / UNIQUE INDEXES (exact names as queried)
-- =============================================================================

ALTER TABLE Core.Permissions        ADD CONSTRAINT UQ_User_System UNIQUE (UserId, SystemId);
ALTER TABLE Core.Users              ADD CONSTRAINT [UQ__Users__AF2DBB988DFB40A8] UNIQUE (EmpId);
ALTER TABLE Flow.FlowDefinitions    ADD CONSTRAINT UQ_FlowDefinitions_FlowCode UNIQUE (FlowCode);
ALTER TABLE Project.ProjectMembers  ADD CONSTRAINT UQ_Project_User UNIQUE (ProjectId, UserId);
ALTER TABLE Project.Projects        ADD CONSTRAINT [UQ__Projects__2F3A4948DB4CB711] UNIQUE (ProjectCode);
ALTER TABLE Project.ProjectTypes    ADD CONSTRAINT [UQ__ProjectT__D4E7DFA8BD8ADE64] UNIQUE (TypeName);
ALTER TABLE Project.TaskAssignees   ADD CONSTRAINT UQ_Task_User UNIQUE (TaskId, UserId);
ALTER TABLE Testing.TestSuites      ADD CONSTRAINT UQ_TestSuites_SuiteCode UNIQUE (SuiteCode);
GO

-- Nullable-FK unique index (SQL Server treats multiple NULLs as distinct, so this
-- still allows unlinked Flow rows while enforcing 1:1 for linked ones)
CREATE UNIQUE INDEX UQ_FlowDefinitions_ProjectId ON Flow.FlowDefinitions(ProjectId);
GO

-- =============================================================================
-- SECTION 4 — NON-UNIQUE INDEXES (exact names/columns as queried)
-- =============================================================================

CREATE INDEX IX_AuditLogs_LogDate ON Core.AuditLogs(LogDate);
CREATE INDEX IX_AuditLogs_User_System ON Core.AuditLogs(UserId, SystemId);
CREATE INDEX IX_Permissions_User_System ON Core.Permissions(UserId, SystemId);
CREATE INDEX IX_Users_EmpId ON Core.Users(EmpId);
CREATE INDEX IX_Users_LoginStatus ON Core.Users(IsActive, IsSuspended, IsOnline);

CREATE INDEX IX_Attachments_Project ON Project.Attachments(ProjectId);
CREATE INDEX IX_Attachments_Task ON Project.Attachments(TaskId);
CREATE INDEX IX_Comments_Project ON Project.Comments(ProjectId);
CREATE INDEX IX_Comments_Task ON Project.Comments(TaskId);
CREATE INDEX IX_Milestones_Owner ON Project.Milestones(OwnerId);
CREATE INDEX IX_Milestones_Project ON Project.Milestones(ProjectId, DueDate);
CREATE INDEX IX_ProjectMembers_User ON Project.ProjectMembers(UserId);
CREATE INDEX IX_Projects_Owner ON Project.Projects(ProjectOwnerId);
CREATE INDEX IX_Projects_ProjectType ON Project.Projects(ProjectTypeId);
CREATE INDEX IX_Projects_Status ON Project.Projects(Status, IsActive);
CREATE INDEX IX_ShowcaseItems_Project ON Project.ShowcaseItems(ProjectId);
CREATE INDEX IX_StatusHistory_Project ON Project.StatusHistory(ProjectId, ChangedDate);
CREATE INDEX IX_StatusHistory_Task ON Project.StatusHistory(TaskId, ChangedDate);
CREATE INDEX IX_TaskAssignees_User ON Project.TaskAssignees(UserId);
CREATE INDEX IX_Tasks_DueDate ON Project.Tasks(DueDate);
CREATE INDEX IX_Tasks_Milestone ON Project.Tasks(MilestoneId);
CREATE INDEX IX_Tasks_Project_Status ON Project.Tasks(ProjectId, Status);
CREATE INDEX IX_TechStacks_Project ON Project.TechStacks(ProjectId);
CREATE INDEX IX_FlowDiagramRows_Flow_Type_Sort ON Flow.FlowDiagramRows(FlowDefinitionId, DiagramType, SortOrder);
GO

-- =============================================================================
-- SECTION 5 — CHECK CONSTRAINTS (exact names/definitions as queried)
-- =============================================================================

ALTER TABLE Flow.FlowDefinitions  ADD CONSTRAINT CK_FlowDefinitions_Status CHECK ([Status]='COMPLETED' OR [Status]='IN_PROGRESS' OR [Status]='PLANNING');
ALTER TABLE Flow.FlowDefinitions  ADD CONSTRAINT CK_FlowDefinitions_WorkType CHECK ([WorkType]='TEAM' OR [WorkType]='SOLO');
ALTER TABLE Flow.FlowDiagramRows  ADD CONSTRAINT CK_FlowDiagramRows_DiagramType CHECK ([DiagramType]='FLOWCHART' OR [DiagramType]='USECASE' OR [DiagramType]='DFD' OR [DiagramType]='SEQUENCE' OR [DiagramType]='ERD' OR [DiagramType]='STATE');
ALTER TABLE Project.Attachments   ADD CONSTRAINT CK_Attachments_RefTarget CHECK ([ProjectId] IS NOT NULL OR [TaskId] IS NOT NULL);
ALTER TABLE Project.Comments      ADD CONSTRAINT CK_Comments_RefTarget CHECK ([ProjectId] IS NOT NULL OR [TaskId] IS NOT NULL);
ALTER TABLE Testing.TestRuns      ADD CONSTRAINT CK_TestRuns_Tool CHECK ([Tool]='robot' OR [Tool]='jest' OR [Tool]='vitest' OR [Tool]='cypress' OR [Tool]='playwright');
ALTER TABLE Testing.TestRuns      ADD CONSTRAINT CK_TestRuns_Environment CHECK ([Environment]='PROD' OR [Environment]='UAT' OR [Environment]='SIT' OR [Environment]='DEV');
ALTER TABLE Testing.TestRuns      ADD CONSTRAINT CK_TestRuns_Status CHECK ([Status]='skipped' OR [Status]='partial' OR [Status]='failed' OR [Status]='passed');
GO

-- =============================================================================
-- SECTION 6 — MASTER / LOOKUP SEED DATA (real current rows from the live DB)
-- =============================================================================

-- Core.SystemList — module registry (Permissions.SystemId FKs into this)
-- หมายเหตุ: SystemId เป็น VARCHAR(50) PRIMARY KEY ธรรมดา ไม่ใช่ Identity Column จึงไม่ต้องใช้
-- SET IDENTITY_INSERT (เดิมสคริปต์นี้เคยใส่ไว้ผิด ซึ่งจะทำให้รันจริงแล้วพัง — แก้ไขแล้ว)
INSERT INTO Core.SystemList (SystemId, SystemName, Description, IsActive) VALUES
    (N'CORE',     N'Core Management',            N'ระบบบริหารจัดการหลัก สิทธิ์ และความปลอดภัย', 1),
    (N'PLANNING', N'งานเดี่ยว (Solo)',           N'ระบบวางแผนงานเดี่ยว — บริหารจัดการโปรเจกต์ที่ทำคนเดียว', 1),
    (N'PROJECT',  N'งานทีม (Team)',              N'ระบบติดตามงานโปรเจกต์ทีม — บริหารจัดการโปรเจกต์ที่ทำร่วมกับทีม', 1),
    (N'SOLO',     N'Project Solo Management',    N'ระบบบริหารจัดการโปรเจกต์เดี่ยว', 1),
    (N'TEAM',     N'Project Team Management',    N'ระบบบริหารจัดการโปรเจกต์ทีม', 1),
    (N'FLOW',     N'Project Flow Architecture',  N'ระบบออกแบบและติดตามผังการทำงานของโปรเจกต์', 1),
    (N'PRESENT',  N'สถานีนำเสนอผลงาน (Present Station)', N'ศูนย์รวม Showcase ผลงาน การสาธิตระบบ และ Media Lightbox Gallery', 1),
    (N'TESTING',  N'Tester Automation',          N'ระบบบันทึกและติดตามผลการทดสอบอัตโนมัติของโปรเจกต์ (Solo/Team)', 1),
    (N'VISITOR',  N'โหมดผู้เยี่ยมชม (Visitor Mode)', N'สำหรับผู้บริหาร/หัวหน้างานเข้าดูภาพรวมโปรเจกต์ของสมาชิกแต่ละคนแบบดูอย่างเดียว (View Only)', 1);
GO

-- Core.Users — Default Admin Account (ให้ Login เข้าใช้งานได้ทันทีหลัง Restore บนฐานข้อมูลเปล่า)
-- EmpId: ADMIN   Password: Admin@123   — แนะนำให้เปลี่ยนรหัสผ่านทันทีหลังใช้งานจริง
-- PasswordHash ด้านล่าง Hash มาจริงด้วย BCrypt.Net-Next (Work Factor 11, Library เดียวกับที่ AuthService ใช้
-- Verify) ผ่าน UsersController จริงแล้ว Capture ค่ามาใส่ — ไม่ใช่ค่าที่เดา/พิมพ์เอง จึง Login ได้จริงทันที
INSERT INTO Core.Users (EmpId, PasswordHash, FullName, UserLevel, IsSuperAdmin, IsSuspended, IsOnline, IsActive)
VALUES (N'ADMIN', '$2a$11$yTVHao/VxKY0R7Xs3Ty7g.ckZerG72aQUFJVqnR1uNeMbC8Fx5Qfu', N'System Administrator', 7, 1, 0, 0, 1);
GO

-- Core.Permissions — ให้สิทธิ์ Default Admin เข้าถึงทุกโมดูลใน Core.SystemList แบบเต็มสิทธิ์
INSERT INTO Core.Permissions (UserId, SystemId, CanView, CanAdd, CanEdit, CanDelete, CanApprove, CanReject)
SELECT u.UserId, s.SystemId, 1, 1, 1, 1, 1, 1
FROM Core.Users u
CROSS JOIN Core.SystemList s
WHERE u.EmpId = N'ADMIN';
GO

-- Project.ProjectTypes — project-type templates used by AutoGeneratePhasesAsync
SET IDENTITY_INSERT Project.ProjectTypes ON;
INSERT INTO Project.ProjectTypes (ProjectTypeId, TypeName, Description, IsActive, SortOrder) VALUES
    (1, N'Web Application',     NULL, 1, 1),
    (2, N'Mobile Application',  NULL, 1, 2),
    (3, N'API / Microservice',  NULL, 1, 3),
    (4, N'Desktop Application', NULL, 1, 4);
SET IDENTITY_INSERT Project.ProjectTypes OFF;
GO

-- Project.Departments — "หน่วยงาน" dropdown master data
SET IDENTITY_INSERT Project.Departments ON;
INSERT INTO Project.Departments (DepartmentId, DepartmentName, IsActive, SortOrder) VALUES
    (1, N'ระบบดิจิตอลและIT', 1, 1),
    (2, N'ฝ่ายซ่อมบำรุง', 1, 2),
    (3, N'ฝ่ายคลังสินค้าและจัดส่ง', 1, 3),
    (4, N'ฝ่ายทรัพยากรบุคคล', 1, 4);
SET IDENTITY_INSERT Project.Departments OFF;
GO

-- Project.TechStackCatalog — Stack "ประเภท/ชื่อ/Layer" dropdown master data (3 option groups: TYPE/NAME/LAYER)
-- TypeId บนแถว NAME ผูกกลับไปแถว TYPE ต้นทาง (Self-Reference) — ใช้กรอง Dropdown "ชื่อ" ตาม "ประเภท" ที่เลือก
-- (Resync เต็มรูปแบบจากฐานข้อมูลจริง ณ วันที่ทำ Data Isolation รอบ Stack/Library — ของเดิมในไฟล์นี้เก่ากว่าฐาน
-- ข้อมูลจริงมาก มีแค่ 16 แถว ขาดอีก 38 แถวที่ถูกเพิ่มเข้าไปตรงๆ ในฐานข้อมูลระหว่างพัฒนาโดยไม่เคย Sync กลับมาที่นี่)
SET IDENTITY_INSERT Project.TechStackCatalog ON;
INSERT INTO Project.TechStackCatalog (CatalogId, OptionGroup, OptionValue, TypeId, IsActive, SortOrder) VALUES
    -- TYPE (10)
    (1,  N'TYPE',  N'ภาษา (Language)',              NULL, 1, 1),
    (2,  N'TYPE',  N'Framework',                     NULL, 1, 2),
    (3,  N'TYPE',  N'Library / Package',             NULL, 1, 3),
    (4,  N'TYPE',  N'Database',                      NULL, 1, 4),
    (17, N'TYPE',  N'AI / LLM Tool',                 NULL, 1, 5),
    (18, N'TYPE',  N'UI/UX & Design Tool',           NULL, 1, 6),
    (19, N'TYPE',  N'Testing & QA',                  NULL, 1, 7),
    (20, N'TYPE',  N'API & Communication Protocol',  NULL, 1, 8),
    (51, N'TYPE',  N'RPA / Automation',              NULL, 1, 9),
    (54, N'TYPE',  N'DevOps / Infra Tool',           NULL, 1, 10),
    -- NAME (36) — TypeId อ้างถึง CatalogId ของแถว TYPE ด้านบน
    (5,  N'NAME',  N'Next.js',            2,  1, 1),
    (6,  N'NAME',  N'React.js',           2,  1, 2),
    (7,  N'NAME',  N'TypeScript',         1,  1, 3),
    (8,  N'NAME',  N'ASP.NET Core',       2,  1, 4),
    (9,  N'NAME',  N'SQL Server',         4,  1, 5),
    (10, N'NAME',  N'Tailwind CSS',       3,  1, 6),
    (11, N'NAME',  N'Zustand',            3,  1, 7),
    (12, N'NAME',  N'Docker',             54, 1, 8),
    (21, N'NAME',  N'Python',             1,  1, 9),
    (22, N'NAME',  N'HTML5',              1,  1, 10),
    (23, N'NAME',  N'CSS3',               1,  1, 11),
    (24, N'NAME',  N'JavaScript',         1,  1, 12),
    (25, N'NAME',  N'Node.js',            2,  1, 13),
    (26, N'NAME',  N'WPF',                2,  1, 14),
    (27, N'NAME',  N'MVVM Architecture',  2,  1, 15),
    (28, N'NAME',  N'C#',                 1,  1, 16),
    (29, N'NAME',  N'C++',                1,  1, 17),
    (30, N'NAME',  N'C',                  1,  1, 18),
    (31, N'NAME',  N'Java',               1,  1, 19),
    (32, N'NAME',  N'MongoDB',            4,  1, 20),
    (33, N'NAME',  N'PostgreSQL',         4,  1, 21),
    (34, N'NAME',  N'REST API',           20, 1, 22),
    (35, N'NAME',  N'WebSocket',          20, 1, 23),
    (36, N'NAME',  N'SignalR',            20, 1, 24),
    (37, N'NAME',  N'PostCSS',            3,  1, 25),
    (38, N'NAME',  N'ESLint',             19, 1, 26),
    (39, N'NAME',  N'Figma',              18, 1, 27),
    (40, N'NAME',  N'Uiverse',            18, 1, 28),
    (43, N'NAME',  N'Lovable',            17, 1, 29),
    (44, N'NAME',  N'v0 by Vercel',       17, 1, 30),
    (45, N'NAME',  N'Gemini',             17, 1, 31),
    (46, N'NAME',  N'Claude Code',        17, 1, 32),
    (47, N'NAME',  N'Anti-gravity',       17, 1, 33),
    (48, N'NAME',  N'ChatGPT',            17, 1, 34),
    (49, N'NAME',  N'Test Automation',    19, 1, 35),
    (50, N'NAME',  N'WinActor',           51, 1, 36),
    -- LAYER (8)
    (13, N'LAYER', N'Frontend',           NULL, 1, 1),
    (14, N'LAYER', N'Backend',            NULL, 1, 2),
    (15, N'LAYER', N'Database',           NULL, 1, 3),
    (16, N'LAYER', N'DevOps',             NULL, 1, 4),
    (41, N'LAYER', N'Testing / QA',       NULL, 1, 5),
    (42, N'LAYER', N'Design / UI-UX',     NULL, 1, 6),
    (52, N'LAYER', N'AI / Automation',    NULL, 1, 7),
    (53, N'LAYER', N'Automation (RPA)',   NULL, 1, 8);
SET IDENTITY_INSERT Project.TechStackCatalog OFF;
GO

-- =============================================================================
-- SECTION 7 — VIEWS (Phase 7: ลด Query ซ้ำซ้อนสำหรับหน้าที่เรียกบ่อย)
-- =============================================================================

-- สรุปสถิติต่อโปรเจกต์ (จำนวน Task/Milestone/สมาชิก) สำหรับหน้า Dashboard และรายงานภาพรวม
-- ลดการยิง COUNT(*) แยกหลายรอบต่อโปรเจกต์ในฝั่ง Application
GO
CREATE VIEW Project.vw_ProjectDashboardSummary AS
SELECT
    p.ProjectId,
    p.ProjectCode,
    p.ProjectName,
    p.ProjectOwnerId,
    p.Status,
    p.IsActive,
    (SELECT COUNT(*) FROM Project.Tasks t WHERE t.ProjectId = p.ProjectId) AS TotalTasks,
    (SELECT COUNT(*) FROM Project.Tasks t WHERE t.ProjectId = p.ProjectId AND t.Status = 'DONE') AS CompletedTasks,
    (SELECT COUNT(*) FROM Project.Milestones m WHERE m.ProjectId = p.ProjectId) AS TotalMilestones,
    (SELECT COUNT(*) FROM Project.ProjectMembers pm WHERE pm.ProjectId = p.ProjectId AND pm.IsActive = 1) AS MemberCount
FROM Project.Projects p;
GO

-- =============================================================================
-- SECTION 8 — STORED PROCEDURES (Phase 7: Operation ที่ซับซ้อน/เรียกบ่อย)
-- =============================================================================

-- คืนรายการ ProjectId ที่ @UserId เข้าถึงได้ (เป็นเจ้าของ หรือเป็นสมาชิกทีมที่ Active) — กติกาเดียวกับ
-- ProjectAccess.For(userId) ฝั่ง Backend (backend/Services/ProjectAccess.cs) ใช้สำหรับ Query/รายงานเฉพาะกิจนอกแอป
GO
CREATE PROCEDURE Core.sp_GetAccessibleProjectIds
    @UserId INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT DISTINCT p.ProjectId
    FROM Project.Projects p
    LEFT JOIN Project.ProjectMembers pm ON pm.ProjectId = p.ProjectId AND pm.UserId = @UserId AND pm.IsActive = 1
    WHERE p.IsActive = 1 AND (p.ProjectOwnerId = @UserId OR pm.ProjectMemberId IS NOT NULL);
END;
GO

-- ลบโปรเจกต์แบบ Hard Delete พร้อมข้อมูลลูกทั้งหมด สำหรับใช้งานตรงจาก DB/สคริปต์ Ops เท่านั้น
-- (แอปจริงลบผ่าน EF ใน ProjectSoloService/ProjectTeamService.DeleteProjectAsync ซึ่งทำสิ่งเดียวกันนี้
-- อยู่แล้วผ่าน ON DELETE CASCADE ของ FK ส่วนใหญ่ + เคลียร์ตารางที่เป็น NoAction ด้วยโค้ด C# เอง)
GO
CREATE PROCEDURE Project.sp_DeleteProjectCascade
    @ProjectId INT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRAN;
    BEGIN TRY
        DELETE FROM Project.StatusHistory WHERE ProjectId = @ProjectId
            OR TaskId IN (SELECT TaskId FROM Project.Tasks WHERE ProjectId = @ProjectId);
        DELETE FROM Project.Projects WHERE ProjectId = @ProjectId;
        COMMIT TRAN;
    END TRY
    BEGIN CATCH
        ROLLBACK TRAN;
        THROW;
    END CATCH;
END;
GO

-- =============================================================================
-- SECTION 9 — TRIGGERS (Phase 7: เท่าที่จำเป็นจริงๆ เพื่อไม่ให้กระทบ Performance)
-- =============================================================================

-- Sync Project.ProgressPercent อัตโนมัติจากค่าเฉลี่ย ProgressPercent ของ Task ระดับบนสุด (ไม่รวม Subtask)
-- ทุกครั้งที่มี Task ถูกเพิ่ม/แก้ไขในโปรเจกต์นั้น — กันไม่ให้ Progress ของโปรเจกต์เพี้ยนไปจาก Task จริง
GO
CREATE TRIGGER Project.Trg_UpdateProjectProgress
ON Project.Tasks
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH AffectedProjects AS (
        SELECT DISTINCT ProjectId FROM inserted
    )
    UPDATE p
    SET p.ProgressPercent = ISNULL(t.AvgProgress, 0),
        p.UpdatedDate = SYSDATETIMEOFFSET()
    FROM Project.Projects p
    INNER JOIN AffectedProjects ap ON ap.ProjectId = p.ProjectId
    OUTER APPLY (
        SELECT AVG(ProgressPercent) AS AvgProgress
        FROM Project.Tasks
        WHERE ProjectId = p.ProjectId AND ParentTaskId IS NULL
    ) t;
END;
GO

-- Denormalize Project.Projects.OwnerEmpId/OwnerName จาก Core.Users ให้เปิดตาราง Projects ตรงๆ
-- (ไม่ JOIN) แล้วรู้ทันทีว่าโปรเจกต์เป็นของใคร — Sync 2 ทิศทาง: ตอนตั้ง/เปลี่ยนเจ้าของ Project และ
-- ตอน User เจ้าของเปลี่ยนชื่อ/EmpId ของตัวเอง
GO
CREATE TRIGGER Project.Trg_SyncProjectOwnerDenorm
ON Project.Projects
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(ProjectOwnerId) RETURN;

    UPDATE p
    SET p.OwnerEmpId = u.EmpId,
        p.OwnerName = u.FullName
    FROM Project.Projects p
    INNER JOIN inserted i ON i.ProjectId = p.ProjectId
    INNER JOIN Core.Users u ON u.UserId = i.ProjectOwnerId;
END;
GO

CREATE TRIGGER Core.Trg_SyncProjectOwnerDenormFromUser
ON Core.Users
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT (UPDATE(EmpId) OR UPDATE(FullName)) RETURN;

    UPDATE p
    SET p.OwnerEmpId = i.EmpId,
        p.OwnerName = i.FullName
    FROM Project.Projects p
    INNER JOIN inserted i ON i.UserId = p.ProjectOwnerId;
END;
GO

-- ลบ Log เก่าอายุเกิน 90 วันอัตโนมัติทุกครั้งที่มีการเขียน Log ใหม่ (Batch เล็กๆ ครั้งละ 500 แถว กัน Table Lock)
-- ป้องกัน Core.AuditLogs โตไม่มีที่สิ้นสุดโดยไม่ต้องพึ่ง Job/Maintenance Plan แยกต่างหาก
GO
CREATE TRIGGER Core.Trg_AutoCleanup_AuditLogs
ON Core.AuditLogs
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    -- ลบ Log ที่เก่ากว่า 90 วัน
    -- ใช้ BATCH DELETE ขนาดเล็ก เพื่อป้องกัน Table Lock ตอนตารางมีขนาดใหญ่
    DELETE TOP (500) FROM Core.AuditLogs
    WHERE LogDate < DATEADD(DAY, -90, SYSDATETIMEOFFSET());
END;
GO

-- =============================================================================
-- SECTION 10 — REPORTING VIEWS (อ่านอย่างเดียว ไม่เปลี่ยนพฤติกรรมการเขียนข้อมูลใดๆ)
-- รวม JOIN/Projection ที่ Service หลายจุดเขียนซ้ำกันไว้ในที่เดียว ให้ Query จริงหรือ Report ในอนาคต
-- เรียกใช้ได้ตรงๆ แทนการต่อ JOIN เองยาวๆ ทุกครั้ง — ดู create_reporting_views.sql (root) สำหรับต้นฉบับ
-- =============================================================================

CREATE VIEW Core.vw_UserPermissionSummary AS
SELECT
    u.UserId,
    u.EmpId,
    u.FullName,
    u.UserLevel,
    u.IsSuperAdmin,
    u.IsSuspended,
    u.IsActive,
    u.IsOnline,
    u.DivisionName,
    u.DepartmentName,
    u.LastLoginDate,
    COUNT(perm.PermissionId)                                   AS SystemsGranted,
    SUM(CASE WHEN perm.CanView    = 1 THEN 1 ELSE 0 END)       AS CanViewCount,
    SUM(CASE WHEN perm.CanAdd     = 1 THEN 1 ELSE 0 END)       AS CanAddCount,
    SUM(CASE WHEN perm.CanEdit    = 1 THEN 1 ELSE 0 END)       AS CanEditCount,
    SUM(CASE WHEN perm.CanDelete  = 1 THEN 1 ELSE 0 END)       AS CanDeleteCount,
    SUM(CASE WHEN perm.CanApprove = 1 THEN 1 ELSE 0 END)       AS CanApproveCount,
    SUM(CASE WHEN perm.CanReject  = 1 THEN 1 ELSE 0 END)       AS CanRejectCount
FROM Core.Users u
LEFT JOIN Core.Permissions perm ON perm.UserId = u.UserId
GROUP BY
    u.UserId, u.EmpId, u.FullName, u.UserLevel, u.IsSuperAdmin, u.IsSuspended, u.IsActive,
    u.IsOnline, u.DivisionName, u.DepartmentName, u.LastLoginDate;
GO

CREATE VIEW Project.vw_ProjectOverview AS
SELECT
    p.ProjectId,
    p.ProjectCode,
    p.ProjectName,
    p.Description,
    p.ProjectTypeId,
    pt.TypeName                                                        AS ProjectTypeName,
    p.DivisionName,
    p.RequesterName,
    p.ProjectOwnerId,
    ownerUser.FullName                                                 AS OwnerName,
    p.CreatedBy,
    creatorUser.FullName                                               AS CreatedByName,
    p.Status,
    p.Priority,
    p.StartDate,
    p.EndDate,
    p.ProgressPercent,
    p.IsActive,
    p.CreatedDate,
    p.UpdatedDate,
    (SELECT COUNT(*) FROM Project.ProjectMembers pm WHERE pm.ProjectId = p.ProjectId) AS MemberCount,
    CASE WHEN EXISTS (SELECT 1 FROM Project.ProjectMembers pm2 WHERE pm2.ProjectId = p.ProjectId)
         THEN 'TEAM' ELSE 'SOLO' END                                   AS WorkType
FROM Project.Projects p
LEFT JOIN Project.ProjectTypes pt   ON pt.ProjectTypeId = p.ProjectTypeId
LEFT JOIN Core.Users ownerUser      ON ownerUser.UserId = p.ProjectOwnerId
LEFT JOIN Core.Users creatorUser    ON creatorUser.UserId = p.CreatedBy;
GO

CREATE VIEW Project.vw_ProjectOwnerStats AS
SELECT
    u.UserId,
    u.EmpId,
    u.FullName,
    u.UserLevel,
    u.DivisionName,
    u.DepartmentName,
    COUNT(p.ProjectId)          AS ProjectCount,
    MAX(p.CreatedDate)          AS LatestProjectDate
FROM Core.Users u
JOIN Project.Projects p ON p.ProjectOwnerId = u.UserId AND p.IsActive = 1
WHERE u.IsActive = 1 AND u.IsSuspended = 0
GROUP BY u.UserId, u.EmpId, u.FullName, u.UserLevel, u.DivisionName, u.DepartmentName;
GO

CREATE VIEW Project.vw_TaskProgress AS
SELECT
    t.ProjectId,
    COUNT(*)                                                    AS TotalTasks,
    SUM(CASE WHEN t.Status = 'DONE' THEN 1 ELSE 0 END)          AS CompletedTasks,
    CASE WHEN COUNT(*) = 0 THEN 0
         ELSE CAST(ROUND(100.0 * SUM(CASE WHEN t.Status = 'DONE' THEN 1 ELSE 0 END) / COUNT(*), 0) AS INT)
    END                                                          AS CompletionPercent
FROM Project.Tasks t
GROUP BY t.ProjectId;
GO

CREATE VIEW Flow.vw_FlowOverview AS
SELECT
    f.FlowDefinitionId,
    f.ProjectId,
    f.FlowCode,
    f.Name,
    f.Description,
    f.Status,
    f.WorkType,
    f.StartDate,
    f.EndDate,
    f.ProgressPercent,
    f.SystemType,
    f.ModuleList,
    f.DfdLevel,
    f.CreatedBy,
    creatorUser.FullName AS CreatedByName,
    f.IsActive,
    f.CreatedDate,
    f.UpdatedDate,
    (SELECT COUNT(*) FROM Flow.FlowDiagramRows r WHERE r.FlowDefinitionId = f.FlowDefinitionId)              AS TotalDiagramRows,
    (SELECT COUNT(DISTINCT r2.DiagramType) FROM Flow.FlowDiagramRows r2 WHERE r2.FlowDefinitionId = f.FlowDefinitionId) AS DiagramTypesFilled
FROM Flow.FlowDefinitions f
LEFT JOIN Core.Users creatorUser ON creatorUser.UserId = f.CreatedBy;
GO
